// SPDX-License-Identifier: GPL-3.0-or-later
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),zlib=require('zlib');
const {chromium}=require(process.env.FLAN36_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'build/themes-print');fs.mkdirSync(out,{recursive:true});
const html=fs.readFileSync(path.join(root,'docs/index.html'));const scene=JSON.parse(zlib.gunzipSync(Buffer.from(html.toString().match(/<script id="scene-data" type="application\/octet-stream">([\s\S]*?)<\/script>/)[1],'base64')));
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.FLAN36_BROWSER?{executablePath:process.env.FLAN36_BROWSER}:{})});try{
 const context=await browser.newContext({viewport:{width:1440,height:960},acceptDownloads:true}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 const url=process.env.FLAN36_VIEWER_URL||'file://'+path.join(root,'docs/index.html');await p.goto(url);await p.waitForFunction(()=>document.querySelector('#config-status').textContent.includes('Saved'),null,{timeout:60000});
 async function save(name){await p.click('#nav-files');const wait=p.waitForEvent('download');await p.click('#save-config');const d=await wait,file=path.join(out,name+'.json');await d.saveAs(file);return JSON.parse(fs.readFileSync(file));}
 async function color(id,value){await p.locator(id).evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},value);}
 const initial=await save('initial');await p.click('#part-base');await p.click('[data-case=rim]');await p.click('#part-lid');await p.click('[data-style=handheld]');await p.click('#part-base');await p.locator('#case-cover').uncheck();
 await p.click('#nav-themes');assert.equal(await p.locator('[data-theme]').count(),16);assert.equal(new Set(await p.locator('#themes-grid img').evaluateAll(a=>a.map(x=>x.src))).size,16);
 await p.locator('[data-theme=cyber-mint]').focus();await p.keyboard.press('Enter');let c=await save('theme');assert.equal(c.cases.left.style,'rim');assert.equal(c.frames.left.style,'handheld');assert.equal(c.cases.left.cover,false);assert.equal(c.cases.left.base_color,c.frames.left.color);assert.equal(c.cases.left.match_frame,true);for(const side of ['left','right'])for(const ref of Object.keys(c.keycaps[side])){assert.equal(c.keycaps[side][ref].variant,initial.keycaps[side][ref].variant);assert.equal(c.keycaps[side][ref].rotation_deg,initial.keycaps[side][ref].rotation_deg);}assert.notDeepEqual(c.keycaps,initial.keycaps);
 await p.click('#part-base');await p.click('#case-target [data-side=left]');await color('#case-base_color','#bb2244');await color('#case-plate_color','#272737');c=await save('custom-case');assert.equal(c.frames.left.color,'#bb2244');assert.notEqual(c.frames.left.color,c.frames.right.color);
 await p.click('#part-lid');await p.click('#frame-target [data-side=left]');await color('#frame-color','#cc5533');await color('#frame-detail','#313131');await color('#frame-accent','#eeee88');await color('#frame-secondary','#6688ee');c=await save('custom-frame');assert.equal(c.cases.left.base_color,'#cc5533');assert.deepEqual(c.frames.left.accents,{detail:'#313131',accent:'#eeee88',secondary:'#6688ee'});
 await p.click('#part-lid');await p.click('#frame-target [data-side=left]');await p.click('[data-style=tv]');let mixed=await save('mixed');assert.equal(mixed.frames.left.color,'#cc5533');assert.equal(mixed.frames.right.style,'handheld');assert.equal(mixed.cases.right.cover,false);assert.deepEqual(mixed.frames.left.accents,c.frames.left.accents);
 await p.reload();await p.waitForFunction(()=>document.querySelector('#config-status').textContent.includes('Restored'),null,{timeout:60000});assert.deepEqual(await save('reloaded'),mixed);
 // Eye/Solo/explosion never determine printable selection.
 await p.click('#part-mcu');await p.click('#isolate-selection');await p.locator('#explode').evaluate(e=>{e.value='70';e.dispatchEvent(new Event('input',{bubbles:true}));});await p.click('#nav-files');await p.selectOption('#print-scope','complete');
 let wait=p.waitForEvent('download');await p.click('#print-kit');let d=await wait;await d.saveAs(path.join(out,'complete.zip'));
 await p.selectOption('#print-half','left');await p.selectOption('#print-scope','shells');wait=p.waitForEvent('download');await p.click('#print-kit');d=await wait;await d.saveAs(path.join(out,'left-shells.zip'));
 // Custom case and all four frame colors also survive GLB export.
 wait=p.waitForEvent('download');await p.click('#glb');d=await wait;const glbPath=path.join(out,'mixed.glb');await d.saveAs(glbPath);const bytes=fs.readFileSync(glbPath),gltf=JSON.parse(bytes.toString('utf8',20,20+bytes.readUInt32LE(12)));
 const assembly=gltf.nodes.find(n=>n.extras?.configuration);assert.deepEqual(assembly.extras.configuration,mixed);
 const linear=h=>{const v=parseInt(h,16)/255;return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4);};
 for(const node of gltf.nodes.filter(n=>n.extras&&(['base','plate'].includes(n.extras.group)||n.extras.frame_style))){const side=node.extras.side,group=node.extras.group,colors=group==='lid'?[mixed.frames[side].color,...['detail','accent','secondary'].map(k=>mixed.frames[side].accents[k])]:[mixed.cases[side][group+'_color']],primitives=gltf.meshes[node.mesh].primitives;assert.equal(primitives.length,colors.length);for(const [i,hex] of colors.entries()){const actual=gltf.materials[primitives[i].material].pbrMetallicRoughness.baseColorFactor;[1,3,5].map(j=>linear(hex.slice(j,j+2))).forEach((v,j)=>assert.ok(Math.abs(v-actual[j])<1e-5));}}
 const bad=JSON.parse(JSON.stringify(mixed));bad.cases.left.base_color='#nothex';await p.locator('#load-config').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});assert.equal(await p.locator('#config-status').getAttribute('data-error'),'true');assert.deepEqual(await save('after-bad'),mixed);
 // Each new design must reach the actual downloadable print kit.
 await p.click('#part-base');await p.click('#case-target [data-side=left]');await p.locator('#case-cover').check();
 for(const style of ['handheld','tv','cyberpunk','cartridge','arcade','mecha','kintsugi']){
  await p.click('#part-lid');await p.click('#frame-target [data-side=left]');await p.click(`[data-style=${style}]`);
  await p.click('#nav-files');await p.selectOption('#print-half','left');await p.selectOption('#print-scope','shells');
  const pending=p.waitForEvent('download');await p.click('#print-kit');const kit=await pending;await kit.saveAs(path.join(out,style+'-shells.zip'));assert.equal(await kit.failure(),null);
 }
 await p.click('#default-config');await p.click('#reset');await p.click('#part-base');await p.click('[data-case=rim]');await p.click('#part-lid');await p.click('[data-style=cyberpunk]');await p.click('#nav-themes');await p.click('[data-theme=cyber-mint]');await p.screenshot({path:path.join(out,'themes-desktop.png')});
 await p.click('#part-mcu');await p.click('#isolate-selection');await p.selectOption('#half','left');await p.selectOption('#view','top');await p.mouse.move(10,20);await p.keyboard.press('Escape');await p.locator('#canvas').screenshot({path:path.join(out,'nano-v2.png'),style:'.stage-label,#leader-lines{opacity:0!important}'});
 for(const width of [390,320]){await p.setViewportSize({width,height:844});await p.click('#reset');await p.click('#nav-themes');const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);const visible=await p.locator('.part-item,.section-links button,#collapse-detail').evaluateAll(a=>a.map(e=>{const r=e.getBoundingClientRect();return r.x>=0&&r.y>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1;}));assert.equal(visible.length,16);assert(visible.every(Boolean));await p.screenshot({path:path.join(out,`themes-${width}.png`)});}
 await p.emulateMedia({reducedMotion:'reduce'});await p.locator('[data-theme=pocket]').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('[data-theme=pocket]').getAttribute('aria-pressed'),'true');
 assert.deepEqual(errors,[]);await context.close();
 const recovery=await browser.newContext();await recovery.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('denied')};});const q=await recovery.newPage();await q.goto(url);await q.waitForFunction(()=>document.querySelector('#config-status').textContent.includes('storage unavailable'),null,{timeout:60000});await q.click('#nav-themes');await q.click('[data-theme=matcha]');assert.equal(await q.locator('[data-theme=matcha]').getAttribute('aria-pressed'),'true');await recovery.close();
 const report={checker_sha256:crypto.createHash('sha256').update(fs.readFileSync(__filename)).digest('hex'),viewer_sha256:crypto.createHash('sha256').update(html).digest('hex'),target:process.env.FLAN36_VIEWER_URL?'public URL':'local file',themes:16,preview_images_distinct:16,linked_colors_bidirectional:true,mixed_halves:true,preserve_shapes_cover_and_keycap_geometry:true,global_keycap_colors:true,json_and_reload_roundtrip:true,invalid_import_atomic:true,storage_failure_recoverable:true,keyboard_and_reduced_motion:true,mobile_widths:[390,320],individual_selection_ignored_by_printkit:true,custom_case_and_four_frame_colors_in_glb:true,new_frame_print_kits:['handheld','tv','cyberpunk','cartridge','arcade','mecha','kintsugi'],runtime_errors:errors};fs.writeFileSync(path.join(out,'ui.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
