// End-to-end reliability acceptance in disposable browser profiles.
// SPDX-License-Identifier: GPL-3.0-or-later
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),crypto=require('crypto'),zlib=require('zlib');
const root=path.resolve(__dirname,'..'),out=path.join(root,'build/reliability-fix');fs.mkdirSync(out,{recursive:true});
const {chromium}=require(process.env.FLAN36_PLAYWRIGHT_MODULE||'playwright'),slot='flan36.configuration.v1',sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const catalog=JSON.parse(fs.readFileSync(path.join(root,'keycaps/catalog.json'))),copy=structuredClone;
let failPrint=false,badPrint=false,printRequests=0,faultHTML;
const server=http.createServer((req,res)=>{try{const url=new URL(req.url,'http://localhost'),relative=decodeURIComponent(url.pathname).replace(/^\//,'')||'index.html',file=path.resolve(root,'docs',relative);if(!file.startsWith(path.join(root,'docs')+'/'))throw Error('path');if(relative.startsWith('assets/')){printRequests++;if(failPrint){res.writeHead(503);res.end('test fault');return;}if(badPrint){res.end('wrong version');return;}}if(relative==='fault.html'){if(!faultHTML){const html=fs.readFileSync(path.join(root,'docs/index.html'),'utf8'),match=html.match(/<script id="scene-data" type="application\/octet-stream">([\s\S]*?)<\/script>/),scene=JSON.parse(zlib.gunzipSync(Buffer.from(match[1],'base64')));delete scene.geometries['mechanical/revI/right-battery-lead-301230-1.stl'];faultHTML=html.replace(match[1],zlib.gzipSync(JSON.stringify(scene)).toString('base64'));}res.setHeader('Content-Type','text/html');res.end(faultHTML);return;}res.setHeader('Content-Type',relative.endsWith('.html')?'text/html':'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
const result={source_snapshot:require('child_process').execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),online_sha256:sha(fs.readFileSync(path.join(root,'docs/index.html'))),offline_sha256:sha(fs.readFileSync(path.join(root,'docs/offline.html'))),checks:{},errors:[]};
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const local=`http://127.0.0.1:${server.address().port}/`,target=process.env.FLAN36_VIEWER_URL||local;
 const browser=await chromium.launch({headless:true,executablePath:process.env.FLAN36_BROWSER});
 try{
 const ctx=await browser.newContext({viewport:{width:1280,height:900},acceptDownloads:true});
 async function open(context=ctx,url=target){const p=await context.newPage();p.on('pageerror',e=>result.errors.push(e.message));await p.goto(url+(url.includes('?')?'&':'?')+'diagnostics');await p.waitForFunction(()=>window.flan36||!document.querySelector('#error').hidden,null,{timeout:90000});assert.equal(await p.locator('#error').isVisible(),false,await p.locator('#error').textContent());return p;}
 const snap=p=>p.evaluate(()=>window.flan36.snapshot()),idle=p=>p.evaluate(()=>window.flan36.idle());
 async function load(p,c){await p.locator('#load-config').setInputFiles({name:'test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(c))});await idle(p);}
 async function download(p,id,name){const waiting=p.waitForEvent('download',{timeout:90000});await p.click(id);const d=await waiting;await d.saveAs(path.join(out,name));return fs.readFileSync(path.join(out,name));}
 const p=await open();console.log('Ready; checking transitions');assert.equal(await p.evaluate(k=>localStorage.getItem(k),slot),null,'Startup is read only');assert.equal(printRequests,0);
 const initial=(await snap(p)).configuration;await p.click('#view-options');await p.selectOption('#half','left');await p.locator('#explode').fill('29');await p.locator('#explode').dispatchEvent('input');await p.click('#close-view');await p.click('#nav-inspect');await p.locator('#layer-mcu').uncheck();await p.click('#nav-customize');
 const rect=await p.locator('#canvas').boundingBox();await p.mouse.move(rect.x+rect.width*.5,rect.y+rect.height*.45);await p.mouse.wheel(0,-240);await p.mouse.down();await p.mouse.move(rect.x+rect.width*.6,rect.y+rect.height*.51,{steps:5});await p.mouse.up();await p.mouse.down({button:'right'});await p.mouse.move(rect.x+rect.width*.63,rect.y+rect.height*.54,{steps:4});await p.mouse.up({button:'right'});
 function sameView(a,b){assert.deepEqual(b.camera,a.camera,'Camera must stay exact');assert.deepEqual(b.view,a.view,'Layer/half/explosion state must stay exact');assert.deepEqual(b.hidden,a.hidden,'Individual hides must stay exact');assert.deepEqual(b.selected,a.selected,'Selection must stay exact');}
 let count=0;async function unchanged(action,layout=false){const a=await snap(p);await action();await idle(p);await p.waitForTimeout(50);const b=await snap(p);if(layout){assert.ok(Number.isFinite(b.camera.halfHeight)&&b.camera.halfHeight>0);a.camera.halfHeight=b.camera.halfHeight;}sameView(a,b);count++;return b;}
 await unchanged(()=>p.click('[data-case=rim]'));
 await p.click('#edit-frames');await p.click('#frame-target [data-side=left]');await unchanged(()=>p.click('[data-style=gameboy]'));await p.locator('#panel-frames .option-group summary').click();await unchanged(()=>p.fill('#frame-color-hex','#aabbcc'));
 await p.click('#edit-keycaps');await unchanged(()=>p.click('[data-preset=saddle-sculpted]'));
 await p.click('#edit-battery');await p.click('#battery-target [data-side=left]');assert.equal(await p.locator('#battery-target [data-side=left]').getAttribute('aria-pressed'),'true');const beforeBattery=await snap(p);const afterBattery=await unchanged(()=>p.click('[data-battery="301230"]'));assert.equal(afterBattery.configuration.batteries.left,'301230');assert.equal(afterBattery.configuration.batteries.right,beforeBattery.configuration.batteries.right);
 await p.click('#battery-target [data-side=right]');await unchanged(()=>p.click('[data-battery="301230"]'));assert.equal((await snap(p)).configuration.batteries.right,'301230');await p.click('#battery-target [data-side=both]');await unchanged(()=>p.click('[data-battery="adafruit-1570"]'));assert.equal((await snap(p)).configuration.batteries.left,'adafruit-1570');
 await p.click('#nav-themes');const beforeTheme=(await snap(p)).configuration;await unchanged(()=>p.locator('[data-theme]').nth(3).click());const afterTheme=(await snap(p)).configuration;assert.notDeepEqual(afterTheme,beforeTheme);await unchanged(()=>p.click('#undo'));assert.deepEqual((await snap(p)).configuration,beforeTheme);await unchanged(()=>p.click('#redo'));assert.deepEqual((await snap(p)).configuration,afterTheme);
 await unchanged(()=>p.click('#nav-inspect'),true);await unchanged(()=>p.click('#nav-customize'),true);await unchanged(()=>p.setViewportSize({width:1100,height:820}),true);
 await p.click('#edit-keycaps');await p.locator('#cap-color').evaluate(e=>{e.value='#334455';e.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#undo').click();});await p.waitForTimeout(80);assert.deepEqual((await snap(p)).configuration,beforeTheme,'Undo cancels queued cap painting');
 await p.click('#nav-files');await p.fill('#design-name','My Flan');const named=p.waitForEvent('download');await p.click('#save-config');assert.equal((await named).suggestedFilename(),'My-Flan.json');
 const valid=copy((await snap(p)).configuration);valid.cases.left.match_frame=false;valid.cases.left.base_color='#123456';await unchanged(()=>load(p,valid));
 const preBad=await snap(p),preStored=await p.evaluate(k=>localStorage.getItem(k),slot),bad=copy(valid);bad.cases.left.base_color='#ff0000';bad.frames.right.style='constructor';await load(p,bad);assert.match(await p.locator('#config-status').textContent(),/Invalid frame/);assert.deepEqual(await snap(p),preBad);assert.equal(await p.evaluate(k=>localStorage.getItem(k),slot),preStored);
 console.log('Negative import and GLB');const glb=await download(p,'#glb','atomic.glb'),gltf=JSON.parse(glb.toString('utf8',20,20+glb.readUInt32LE(12))),base=gltf.nodes.find(n=>n.extras?.group==='base'&&n.extras?.side==='left'),material=gltf.materials[gltf.meshes[base.mesh].primitives[0].material].pbrMetallicRoughness.baseColorFactor;
 assert.match(JSON.stringify(gltf),/original keyboard and CAD design/);assert.doesNotMatch(JSON.stringify(gltf),/derived from Piantor/);assert.deepEqual(gltf.nodes.find(n=>n.extras?.configuration).extras.configuration,valid);assert.notDeepEqual(material,[1,0,0,1]);assert.ok(material[0]<material[1]&&material[1]<material[2],'Actual exported base retains #123456, not rejected red');
 const legacy=copy(valid);delete legacy.cases;await unchanged(()=>load(p,legacy));assert.equal((await snap(p)).configuration.cases.left.style,'solid');assert.equal((await snap(p)).configuration.cases.right.cover,true);
 await p.locator('#recovery summary').click();await unchanged(()=>p.click('#default-config'));await unchanged(()=>p.click('#undo'));assert.equal((await snap(p)).configuration.cases.left.style,'solid');
 // The actual print loader is absent on startup, retryable after failures and hash checked.
 if(!process.env.FLAN36_VIEWER_URL){failPrint=true;await p.click('#print-kit');await p.waitForFunction(()=>!document.querySelector('#print-kit').disabled);assert.match(await p.locator('#print-status').textContent(),/Export failed/);failPrint=false;badPrint=true;await p.click('#print-kit');await p.waitForFunction(()=>!document.querySelector('#print-kit').disabled);assert.match(await p.locator('#print-status').textContent(),/do not match/);badPrint=false;}
 console.log('Online kit');const kit=await download(p,'#print-kit','online-kit.zip');require('esbuild').buildSync({stdin:{contents:"export {unzipSync,strFromU8} from 'three/addons/libs/fflate.module.js';",resolveDir:__dirname},bundle:true,platform:'node',format:'cjs',outfile:path.join(out,'zip.cjs')});const {unzipSync}=require(path.join(out,'zip.cjs')),files=unzipSync(kit),manifest=JSON.parse(Buffer.from(files['manifest.json']).toString());assert.equal(manifest.configuration.cases.left.style,'solid');for(const part of manifest.parts){assert.equal(sha(files['STL/'+part.id+'.stl']),part.source_sha256);assert.equal(sha(fs.readFileSync(path.join(root,part.source))),part.source_sha256);}
 result.checks={camera_transitions:count,rejected_import_atomic_glb:true,legacy_solid_kit:true,battery_targets:true,undo_redo_and_pending_paint:true,named_json_export:true,lazy_print_retry_and_hash:true,exact_native_stl_hashes:true};
 // A resource-resolution failure must roll back the entire attempted scene update.
 if(!process.env.FLAN36_VIEWER_URL){const fc=await browser.newContext();const f=await open(fc,local+'fault.html'),before=await snap(f),broken=copy(before.configuration);broken.cases.left.match_frame=false;broken.cases.left.base_color='#ff0000';broken.batteries.right='301230';await load(f,broken);assert.match(await f.locator('#config-status').textContent(),/Geometry unavailable/);assert.deepEqual(await snap(f),before);assert.equal(await f.evaluate(k=>localStorage.getItem(k),slot),null);await f.click('#nav-files');const bytes=await download(f,'#glb','missing-resource.glb'),exported=JSON.parse(bytes.toString('utf8',20,20+bytes.readUInt32LE(12)));assert.deepEqual(exported.nodes.find(n=>n.extras?.configuration).extras.configuration,before.configuration);const base=exported.nodes.find(n=>n.extras?.side==='left'&&n.extras?.group==='base');assert.notDeepEqual(exported.materials[exported.meshes[base.mesh].primitives[0].material].pbrMetallicRoughness.baseColorFactor,[1,0,0,1]);await fc.close();result.checks.missing_resource_atomic_glb=true;}
 // Two genuine tabs wait behind a real Web Lock, then race from the same baseline.
 console.log('Concurrent tabs');const a=await open(),b=await open();await a.evaluate(k=>{window.releaseTestLock=null;window.lockHeld=false;navigator.locks.request(k,()=>new Promise(resolve=>{window.releaseTestLock=resolve;window.lockHeld=true;}));},slot);await a.waitForFunction(()=>window.lockHeld);
 const ca=copy((await snap(a)).configuration),cb=copy(ca);ca.keycaps.left.K01.color='#111222';cb.keycaps.left.K01.color='#aabbcc';await Promise.all([a.locator('#load-config').setInputFiles({name:'a.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(ca))}),b.locator('#load-config').setInputFiles({name:'b.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(cb))})]);await a.evaluate(()=>window.releaseTestLock());await Promise.all([idle(a),idle(b)]);
 const persisted=await a.evaluate(k=>({saved:JSON.parse(localStorage.getItem(k)),drafts:Object.keys(localStorage).filter(k=>k.startsWith('flan36.recovery.')).map(k=>JSON.parse(localStorage.getItem(k)))}),slot);const available=[persisted.saved,...persisted.drafts.filter(d=>d.key===slot).map(d=>JSON.parse(d.raw))];assert.ok(available.some(c=>c.keycaps.left.K01.color==='#111222'));assert.ok(available.some(c=>c.keycaps.left.K01.color==='#aabbcc'));result.checks.simultaneous_tabs_preserve_both=true;
 // Closing a tab before its queued shared write runs preserves its latest draft.
 const closing=await open();await a.evaluate(k=>{window.lockHeld=false;navigator.locks.request(k,()=>new Promise(resolve=>{window.releaseTestLock=resolve;window.lockHeld=true;}));},slot);await a.waitForFunction(()=>window.lockHeld);await closing.evaluate(()=>document.querySelector('[data-case=rim]').click());const closingConfig=(await snap(closing)).configuration;await closing.close();assert.ok(await a.evaluate(({slot,cfg})=>Object.keys(localStorage).filter(k=>k.startsWith('flan36.recovery.')).map(k=>JSON.parse(localStorage.getItem(k))).some(d=>d.key===slot&&d.raw===JSON.stringify(cfg)),{slot,cfg:closingConfig}));await a.evaluate(()=>window.releaseTestLock());result.checks.close_while_save_queued=true;
 await a.close();await b.close();
 // The palette library uses the same protected store, including genuine tab conflicts.
 const pa=await open(),pb=await open();
 async function savePalette(page,name){await page.evaluate(name=>{document.querySelector('#cap-palette-name').value=name;document.querySelector('#save-cap-palette').click();},name);}
 await Promise.all([savePalette(pa,'Palette A'),savePalette(pb,'Palette B')]);await Promise.all([idle(pa),idle(pb)]);
 await pb.waitForFunction(()=>Object.keys(localStorage).some(k=>k.startsWith('flan36.recovery.flan36.keycap-palettes')),null,{polling:100}).catch(async e=>{console.log('palette failure',await pa.evaluate(()=>({keys:Object.keys(localStorage),status:document.querySelector('#config-status').textContent})),await pb.locator('#config-status').textContent());throw e;});
 const palettes=await pa.evaluate(()=>{const slot='flan36.keycap-palettes.v1';return [JSON.parse(localStorage.getItem(slot)),...Object.keys(localStorage).filter(k=>k.startsWith('flan36.recovery.')).map(k=>JSON.parse(localStorage.getItem(k))).filter(d=>d.key===slot).map(d=>JSON.parse(d.raw))];});
 assert.ok(palettes.some(p=>p.palettes.some(x=>x.name==='Palette A')));assert.ok(palettes.some(p=>p.palettes.some(x=>x.name==='Palette B')));await pa.close();await pb.close();result.checks.palette_tab_conflicts=true;
 // Rejected stored bytes survive startup, an edit, reload and explicit recovery download.
 console.log('Storage recovery');for(const raw of ['{"schema":"flan36-config-1","revision":"H","color":"#654321"}','{broken', 'x'.repeat(100001)]){
  const cx=await browser.newContext({viewport:{width:1280,height:900}});await cx.addInitScript(({slot,raw})=>{if(!sessionStorage.getItem('seeded')){localStorage.setItem(slot,raw);sessionStorage.setItem('seeded','yes');}},{slot,raw});const q=await open(cx);assert.equal(await q.evaluate(k=>localStorage.getItem(k),slot),raw);await q.click('[data-case=rim]');await idle(q);assert.equal(await q.evaluate(k=>localStorage.getItem(k),slot),raw);await q.reload();await q.waitForFunction(()=>window.flan36);assert.equal(await q.evaluate(k=>localStorage.getItem(k),slot),raw);await q.click('#nav-files');await q.locator('#recovery').evaluate(e=>e.open=true);const bytes=await download(q,'#recovery-list button:first-child','recovered.json');assert.equal(bytes.toString(),raw);await cx.close();
 }
 result.checks.rejected_storage_preserved_and_downloadable=true;
 // Offline artifact has all files, no requests required; compare exact kit contents.
 console.log('Offline and mobile');const off=await browser.newContext({viewport:{width:1280,height:900}});let attempted=0;await off.route(/^https?:/,r=>{attempted++;return r.abort();});const q=await open(off,'file://'+path.join(root,'docs/offline.html'));assert.equal(await q.locator('[download="Flan36-revI.html"]').getAttribute('href'),q.url());await load(q,manifest.configuration);await q.click('#nav-files');const offlineKit=unzipSync(await download(q,'#print-kit','offline-kit.zip'));assert.deepEqual(Object.keys(offlineKit).sort(),Object.keys(files).sort());for(const name of Object.keys(files)){if(name.endsWith('.3mf')){const aa=unzipSync(offlineKit[name]),bb=unzipSync(files[name]);assert.deepEqual(Object.keys(aa).sort(),Object.keys(bb).sort());for(const entry of Object.keys(aa))assert.equal(sha(aa[entry]),sha(bb[entry]),name+':'+entry);}else assert.equal(sha(offlineKit[name]),sha(files[name]),name);}await download(q,'#glb','offline.glb');assert.equal(attempted,0);result.checks.offline_exact_kit_and_glb=true;
 await q.setViewportSize({width:390,height:844});await q.click('#nav-customize');await q.click('#edit-battery');await q.click('#battery-target [data-side=left]');await q.click('[data-battery="301230"]');assert.equal((await snap(q)).configuration.batteries.left,'301230');const controls=await q.locator('.history-controls button:not([hidden])').evaluateAll(nodes=>nodes.map(e=>{const r=e.getBoundingClientRect();return r.x>=0&&r.right<=innerWidth&&r.height>20;}));assert.ok(controls.every(Boolean));await q.screenshot({path:path.join(out,'mobile.png')});await off.close();result.checks.mobile_controls=true;
 // Non-secure/offline runtimes may lack both locks and randomUUID.
 const limited=await browser.newContext();await limited.addInitScript(()=>{Object.defineProperty(navigator,'locks',{value:undefined});Object.defineProperty(crypto,'randomUUID',{value:undefined});});const lp=await open(limited);await lp.click('[data-case=rim]');await idle(lp);assert.equal(await lp.evaluate(k=>localStorage.getItem(k),slot),null);assert.ok(await lp.evaluate(()=>Object.keys(localStorage).some(k=>k.startsWith('flan36.recovery.'))));assert.match(await lp.locator('#config-status').textContent(),/Autosave unavailable/);await limited.close();result.checks.no_locks_or_random_uuid=true;
 // Storage denied still leaves editable/exportable design; no startup or write crash.
 const denied=await browser.newContext({viewport:{width:390,height:844}});await denied.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Denied','SecurityError')}}));const d=await open(denied);await d.click('[data-case=rim]');await idle(d);assert.match(await d.locator('#config-status').textContent(),/only in this tab/);await d.click('#nav-files');const exported=JSON.parse((await download(d,'#save-config','storage-denied.json')).toString());assert.equal(exported.cases.left.style,'rim');await denied.close();result.checks.denied_storage_export=true;
 assert.deepEqual(result.errors,[]);await p.screenshot({path:path.join(out,'desktop.png')});result.passed=true;
 }finally{await browser.close();server.close();fs.writeFileSync(path.join(out,'browser.json'),JSON.stringify(result,null,2)+'\n');}
 console.log(JSON.stringify(result,null,2));
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
