// SPDX-License-Identifier: GPL-3.0-or-later
// Measure usable canvas pixels and the editor lifecycle in isolated browser profiles.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url'),pw=require(process.env.FLAN36_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),engine=process.env.FLAN36_ENGINE||'chromium';
const out=path.join(root,'build/canvas-review');fs.mkdirSync(out,{recursive:true});
const target=process.env.FLAN36_VIEWER_URL||pathToFileURL(path.join(root,'docs/offline.html')).href;
const result={engine,target:target.startsWith('file:')?'offline':target,checks:[],errors:[],physical_phone_tested:false};
// ResizeObserver schedules the renderer on the following animation frame.
const settle=async p=>{await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>requestAnimationFrame(r)))));await p.waitForTimeout(100);};
const snapshot=p=>p.evaluate(()=>window.flan36.snapshot());
function preserved(a,b){const {halfHeight:aa,...ac}=a.camera,{halfHeight:bb,...bc}=b.camera;assert.deepEqual(bc,ac,'Orbit, pan and zoom preserved');for(const k of ['configuration','view','selected','hidden','undo','redo'])assert.deepEqual(b[k],a[k],k+' preserved');assert.ok(Number.isFinite(bb)&&bb>0);}
async function panel(p,mode){if(await p.locator('body').getAttribute('data-panel-open')!=='true'||await p.locator('body').getAttribute('data-mode')!==mode)await p.click('#nav-'+mode);await settle(p);}
async function close(p){if(await p.locator('#workspace').isVisible())await p.click('#panel-close');await settle(p);}
async function framed(p){
 const r=await p.locator('#canvas').boundingBox();
 const png=(await p.screenshot({clip:{x:Math.ceil(r.x)+1,y:Math.ceil(r.y)+1,width:Math.floor(r.width)-2,height:Math.floor(r.height)-2}})).toString('base64');
 fs.writeFileSync(path.join(out,engine+'-canvas.png'),Buffer.from(png,'base64'));
 const bounds=await p.evaluate(async png=>{const i=new Image();i.src='data:image/png;base64,'+png;await i.decode();const c=document.createElement('canvas');c.width=i.width;c.height=i.height;const x=c.getContext('2d');x.drawImage(i,0,0);const {data}=x.getImageData(0,0,c.width,c.height),bg=[...data.slice(0,3)];let x0=c.width,y0=c.height,x1=0,y1=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const n=(y*c.width+x)*4;if(bg.reduce((s,v,j)=>s+Math.abs(v-data[n+j]),0)>40){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}}return {x0,y0,x1,y1,w:c.width,h:c.height};},png);
 assert.ok(bounds.x1>bounds.x0&&bounds.y1>bounds.y0&&bounds.x0>4&&bounds.y0>4&&bounds.x1<bounds.w-5&&bounds.y1<bounds.h-5,'Model pixels fit: '+JSON.stringify(bounds));
 const fill=Math.max((bounds.x1-bounds.x0)/bounds.w,(bounds.y1-bounds.y0)/bounds.h);assert.ok(fill>.70&&fill<.97,'Model uses its limiting dimension: '+fill);return bounds;
}
async function layout(p,label,{compact=false,pixels=true}={}){
 await settle(p);
 const boxes=await p.evaluate(()=>{const c=document.querySelector('#canvas').getBoundingClientRect(),e=document.querySelector('#workspace'),r=e.getBoundingClientRect(),closed=e.hidden,portrait=matchMedia('(max-width:700px),(max-width:1000px) and (orientation:portrait)').matches;return {width:innerWidth,height:innerHeight,closed,portrait,overflow:document.documentElement.scrollWidth>innerWidth,canvas:{x:c.x,y:c.y,width:c.width,height:c.height},area:c.width*c.height/(innerWidth*innerHeight),editorWidth:r.width,overlap:!closed&&c.right>r.left+1&&r.right>c.left+1&&c.bottom>r.top+1&&r.bottom>c.top+1,centerHit:document.elementFromPoint(c.x+c.width/2,c.y+c.height/2)?.id,nav:[...document.querySelectorAll('.app-nav button')].map(e=>{const r=e.getBoundingClientRect();return {width:r.width,height:r.height,visible:r.top>=0&&r.bottom<=innerHeight&&e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))};})};});
 assert.equal(boxes.overflow,false,label+' overflow');assert.equal(boxes.overlap,false,label+' panel overlap');assert.equal(boxes.centerHit,'canvas',label+' canvas hit target');assert.ok(boxes.nav.every(r=>r.visible&&r.width>=44&&r.height>=44),label+' touch targets');
 if(boxes.closed)assert.ok(boxes.area>=.85,label+' closed canvas >=85%');
 if(compact&&boxes.portrait)assert.ok(boxes.area>=.55&&boxes.canvas.height>=220,label+' compact useful canvas');
 if(compact&&!boxes.portrait)assert.ok(boxes.editorWidth<=360.1&&boxes.editorWidth<=boxes.width*.4+.1,label+' default dock width');
 if(pixels)boxes.pixels=await framed(p);result.checks.push({label,...boxes});
}
(async()=>{const b=await pw[engine].launch({headless:true,...(process.env.FLAN36_BROWSER?{executablePath:process.env.FLAN36_BROWSER}:{})});result.browser=await b.version();try{
 const c=await b.newContext({viewport:{width:1440,height:960},hasTouch:true,deviceScaleFactor:1}),p=await c.newPage();p.on('pageerror',e=>result.errors.push(e.message));
 await p.addInitScript(()=>{const read=Response.prototype.text;Response.prototype.text=async function(...args){if(!window.loadingHeld){window.loadingHeld=true;await new Promise(resolve=>window.releaseLoading=resolve);}return read.apply(this,args);};});
 await p.goto(target+(target.includes('?')?'&':'?')+'diagnostics');await p.waitForFunction(()=>window.loadingHeld,null,{timeout:90000});assert.ok(await p.locator('#loading').isVisible(),'Pending geometry has visible status');await p.screenshot({path:path.join(out,engine+'-loading.png')});await p.evaluate(()=>window.releaseLoading());await p.waitForFunction(()=>window.flan36,null,{timeout:90000});await settle(p);
 assert.equal(await p.locator('#loading').isVisible(),false,'Loading status retires when rendered');
 assert.equal(await p.locator('#workspace').isVisible(),false,'Default is only the model');assert.equal(await p.locator('header').count(),0);assert.equal(await p.locator('.view-controls').count(),0);
 for(const [w,h] of [[1440,960],[390,690],[320,568],[430,820],[844,390],[768,1024],[1024,768]]){
  console.log(w+'x'+h);await close(p);const before=await snapshot(p);await p.setViewportSize({width:w,height:h});await settle(p);preserved(before,await snapshot(p));await layout(p,`${w}x${h} closed`);await p.screenshot({path:path.join(out,`${engine}-${w}-closed.png`)});
  await panel(p,'customize');await layout(p,`${w}x${h} compact`,{compact:true});await p.screenshot({path:path.join(out,`${engine}-${w}-compact.png`)});await close(p);assert.equal(await p.evaluate(()=>document.activeElement.id),'nav-customize');preserved(before,await snapshot(p));
  for(const mode of ['inspect','files','about']){await panel(p,mode);await layout(p,`${w}x${h} ${mode}`);await p.screenshot({path:path.join(out,`${engine}-${w}-${mode}.png`)});}
  await p.click('#credits');assert.equal(await p.locator('#licenses details[open]').count(),0);await p.locator('#licenses details summary').first().click();await p.locator('#licenses .dialog-body').evaluate(e=>e.scrollTop=e.scrollHeight);await settle(p);assert.ok(await p.locator('#close-credits').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));await p.keyboard.press('Escape');assert.equal(await p.locator('#licenses').isVisible(),false);assert.equal(await p.locator('#workspace').isVisible(),true);assert.equal(await p.evaluate(()=>document.activeElement.id),'credits');await p.locator('#licenses details').first().evaluate(e=>e.open=false);
  await close(p);await p.click('#view-options');await p.screenshot({path:path.join(out,`${engine}-${w}-view.png`)});await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.id),'view-options');preserved(before,await snapshot(p));
 }
 // The smallest side dock must keep close/category/history controls reachable.
 for(const [width,height] of [[701,390],[844,390],[1440,960]]){
  await close(p);await p.setViewportSize({width,height});await panel(p,'customize');const splitter=p.locator('#panel-resize');
  for(const key of ['Home','End']){
   await splitter.focus();await p.keyboard.press(key);await settle(p);
   const controls=await p.locator('#panel-close,#panel-expand,#editor-category,#undo,#redo').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {id:e.id,inside:r.x>=0&&r.right<=innerWidth&&r.y>=0&&r.bottom<=innerHeight,hit:e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))};}));
   assert.ok(controls.every(e=>e.inside&&e.hit),'Lateral '+width+' '+key+': '+JSON.stringify(controls));
  }
  for(const dx of [-2000,2000]){const r=await splitter.boundingBox();await p.mouse.move(r.x+r.width/2,r.y+r.height/2);await p.mouse.down();await p.mouse.move(Math.max(0,Math.min(width-1,r.x+dx)),r.y+r.height/2,{steps:4});await p.mouse.up();await settle(p);assert.ok(await p.locator('#panel-close').evaluate(e=>{const r=e.getBoundingClientRect();return r.right<=innerWidth&&e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));}
  result.checks.push({label:width+' lateral extremes',controls_reachable:true});
 }
 await p.setViewportSize({width:390,height:690});await panel(p,'customize');
 // Explicit resize, drag and keyboard affordances preserve the camera and saved design.
 const base=await snapshot(p),compact=await p.locator('#canvas').boundingBox();await p.click('#panel-expand');await settle(p);assert.ok((await p.locator('#canvas').boundingBox()).height<compact.height);await p.selectOption('#editor-category','themes');await p.screenshot({path:path.join(out,`${engine}-390-expanded.png`)});await p.click('#panel-expand');await settle(p);assert.ok(Math.abs((await p.locator('#canvas').boundingBox()).height-compact.height)<1);
 const handle=p.locator('#panel-resize'),r=await handle.boundingBox();await p.mouse.move(r.x+r.width/2,r.y+r.height/2);await p.mouse.down();await p.mouse.move(r.x+r.width/2,r.y-64,{steps:4});await p.mouse.up();await settle(p);assert.ok((await p.locator('#canvas').boundingBox()).height<compact.height-40);await handle.focus();await p.keyboard.press('ArrowDown');await settle(p);const afterDrag=await p.locator('#canvas').boundingBox();await close(p);await panel(p,'customize');assert.ok(Math.abs((await p.locator('#canvas').boundingBox()).height-afterDrag.height)<1);preserved(base,await snapshot(p));
 for(const category of ['cases','frames','keycaps','themes','battery']){await p.selectOption('#editor-category',category);assert.ok(await p.locator('#panel-'+category).isVisible());await p.screenshot({path:path.join(out,`${engine}-editor-${category}.png`)});}
 await p.selectOption('#editor-category','themes');await p.locator('#inspector').evaluate(e=>e.scrollTop=180);const scroll=await p.locator('#inspector').evaluate(e=>e.scrollTop);await close(p);await panel(p,'customize');assert.equal(await p.locator('#editor-category').inputValue(),'themes');assert.equal(await p.locator('#inspector').evaluate(e=>e.scrollTop),scroll);await panel(p,'about');await panel(p,'customize');assert.equal(await p.locator('#inspector').evaluate(e=>e.scrollTop),scroll);
 await p.selectOption('#editor-category','cases');await p.locator('#panel-cases .option-group summary').first().click();await p.locator('#case-target [data-side=left]').click();const beforeEdit=await snapshot(p);await p.locator('#case-colors .hex-input').first().fill('#223344');await p.setViewportSize({width:390,height:400});await settle(p);assert.ok(await p.locator('#canvas').isVisible());assert.ok((await p.locator('#canvas').boundingBox()).height>=79);await p.locator('#case-colors .hex-input').first().blur();await p.setViewportSize({width:390,height:690});await settle(p);await p.evaluate(()=>window.flan36.idle());const edited=await snapshot(p);assert.equal(edited.configuration.cases.left.base_color,'#223344');assert.equal(edited.configuration.cases.right.base_color,beforeEdit.configuration.cases.right.base_color);await p.click('#undo');await p.evaluate(()=>window.flan36.idle());assert.deepEqual((await snapshot(p)).configuration,beforeEdit.configuration);await p.click('#redo');await p.evaluate(()=>window.flan36.idle());assert.deepEqual((await snapshot(p)).configuration,edited.configuration);await p.click('#undo');await p.evaluate(()=>window.flan36.idle());
 await panel(p,'inspect');for(const group of ['base','plate','lid','keycaps','switches','pcb','battery','mcu','display','connectors','supports','fasteners']){await p.locator('#part-'+group).tap();const eye=p.locator('#layer-'+group);await eye.scrollIntoViewIfNeeded();const r=await eye.boundingBox();assert.ok(r.width>=44&&r.height>=44);await eye.uncheck();assert.equal((await snapshot(p)).view.layers[group],false);await eye.check();}
 await p.click('#part-base');const selected=await snapshot(p);await p.click('#view-options');await p.keyboard.press('Escape');preserved(selected,await snapshot(p));await p.keyboard.press('Escape');await settle(p);assert.equal(await p.locator('#workspace').isVisible(),false);preserved(selected,await snapshot(p));assert.equal(await p.locator('#part-link').isVisible(),false);await panel(p,'inspect');await p.click('#clear-selection');assert.equal(await p.locator('.part-item[aria-expanded=true]').count(),0);await close(p);
 for(const preset of ['inside','stack','complete']){await p.click('#view-options');await p.click('#'+preset);assert.equal(await p.locator('#view-dialog').isVisible(),false);await layout(p,'preset '+preset);}
 if(engine==='chromium'){const client=await c.newCDPSession(p),r=await p.locator('#canvas').boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2;for(const points of [[{x,y,id:1}],[{x:x-25,y,id:1},{x:x+25,y,id:2}]]){await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points.map((a,i)=>({...a,x:a.x+(i?40:-30),y:a.y+80}))});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}assert.equal((await snapshot(p)).selected,null,'Gestures do not select');}
 await p.click('#fit');await layout(p,'fit after orbit and pinch');const cv=await p.locator('#canvas').boundingBox();await p.mouse.move(cv.width/2,cv.height/2);await p.mouse.wheel(0,-200);await settle(p);const zoomed=await snapshot(p);await panel(p,'customize');await close(p);await p.setViewportSize({width:844,height:390});await settle(p);preserved(zoomed,await snapshot(p));
 assert.deepEqual(result.errors,[]);result.passed=true;result.interactions=['default closed canvas','unobstructed canvas pixels and hit target','compact expanded drag keyboard sizing','close and focus restoration','category scroll and panel size persistence','five editors','12 component eyes','one-half color edit and undo redo','modal Escape then panel Escape preserves selection','long license close remains reachable','presets and gestures','orientation preserves camera and selection','keyboard viewport preserves canvas','no header or floating toolbar'];
 }finally{await b.close();fs.writeFileSync(path.join(out,`${engine}-responsive.json`),JSON.stringify(result,null,2)+'\n');}
 console.log(JSON.stringify({engine,passed:result.passed,checks:result.checks.length,errors:result.errors}));
})().catch(e=>{console.error(e);process.exitCode=1;});
