#!/usr/bin/env python3
"""Public approval gallery from exact frame review artifacts.
SPDX-License-Identifier: GPL-3.0-or-later
"""
import hashlib,html,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'design/proposals/frame-redesign-r6';OUT=ROOT/'docs/frame-proposals'
def run():
    master=json.loads((SOURCE/'master.json').read_text());check=json.loads((SOURCE/'geometry-check.json').read_text())
    digest=hashlib.sha256((SOURCE/'master.json').read_bytes()).hexdigest();assert check['master_sha256']==digest
    OUT.mkdir(parents=True,exist_ok=True)
    assets=['collection.png','collection-a.png','collection-b.png','collection-c.png','native-review.png','native-top.png']
    assets += [k+suffix for k in master['styles'] for suffix in ['-preview.svg','-card.png','-dimensioned.png','.svg']]
    for name in assets:shutil.copy2(SOURCE/name,OUT/name)
    base='https://github.com/eduarbo/flan36/blob/main/design/proposals/frame-redesign-r6/'
    cards=''
    for key,s in master['styles'].items():
        label=html.escape(s['label']);palette=''.join(f'<span><i style="background:{c}"></i><code>{c}</code></span>' for c in s['palette'].values())
        cards+=f'''<article id="{key}"><a class="preview" href="{key}-card.png" aria-label="Enlarge {label}"><img src="{key}-preview.svg" width="240" height="560" alt="{label}: exact solid-color frame proposal" loading="lazy"></a><div class="replaces">New direction for {html.escape(s['replaces'])}</div><h2>{label}</h2><p>{html.escape(s['note'])}</p><div class="palette">{palette}</div><nav aria-label="{label} files"><a href="{key}-dimensioned.png">Dimensions</a><a href="{key}.svg" download>1:1 SVG ↓</a></nav></article>'''
    page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>R6 frame proposals · Flan36</title><style>
:root{color-scheme:light;font:16px/1.5 system-ui,sans-serif;color:#253c37;background:#f6f5f0}*{box-sizing:border-box}body{margin:0}main{max-width:1180px;margin:auto;padding:28px 20px 60px}a{color:inherit;text-underline-offset:4px}a:focus-visible{outline:3px solid #527d63;outline-offset:4px;border-radius:4px}header{max-width:820px;margin:24px 0 32px}h1{font-size:clamp(32px,5vw,54px);line-height:1.1;margin:16px 0}h2{margin:0 0 10px;font-size:25px}p{margin:8px 0 16px}.status,.replaces{font-size:12px;letter-spacing:.065em;text-transform:uppercase;color:#576e60}.replaces{margin-bottom:6px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}article{background:#fffefa;border:1px solid #dce1d7;border-radius:16px;padding:22px;scroll-margin:20px}.preview{display:flex;height:340px;align-items:center;justify-content:center;margin-bottom:24px;border-radius:10px;transition:background .12s}.preview:hover{background:#f2f1e9}.preview img{height:100%;width:auto;max-width:100%}article p{font-size:14px;min-height:104px;color:#4c6058}.palette{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;font-size:12px}.palette span{display:flex;gap:6px;align-items:center}.palette code{user-select:all}.palette i{width:14px;height:14px;border:1px solid #0002;border-radius:3px;flex-shrink:0}nav{display:flex;flex-wrap:wrap;gap:10px;margin:20px 0 0}nav a{padding:10px 12px;min-height:44px;border:1px solid #dce1d7;border-radius:8px;font-size:14px;text-decoration:none}nav a:hover{background:#edf1e8}.native{width:100%;height:auto;border-radius:16px;margin:18px 0}.notes{max-width:880px;margin:40px 0}.hash{overflow-wrap:anywhere;font-size:11px;color:#5d6d64}details{margin:25px 0}summary{cursor:pointer;padding:12px 0;min-height:44px}.back{display:inline-block;padding:8px 0;min-height:44px}@media(max-width:800px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.grid{grid-template-columns:1fr}article p{min-height:0}.preview{height:380px}main{padding:20px 16px}}
</style></head><body><main><a class="back" href="../">← 3D explorer</a><header><div class="status">R6 · proposals awaiting approval</div><h1>Six new directions.</h1><p>Caramelo, Lucha, Hanafuda, Mecha, Cartucho 8 and Terminal. New artwork on the same slim 24 × 56 mm frame, with solid colors and flush details.</p><p>Tap a frame to enlarge it. Each drawing has exact dimensions, HEX colors and matching editable 3D geometry. The main keyboard assembly still uses the existing artwork.</p></header><div class="grid">'''+cards+'''</div><section class="notes"><h2>From these paths to these solids.</h2><p>These renders come from the actual review solids. Each material’s top surface is checked against its source paths, so approval fixes the shapes and palette rather than leaving them to reinterpretation.</p><nav><a href="'''+base+'''Artwork-R6.FCStd">Open FreeCAD review</a><a href="'''+base+'''master.json">Dimensions &amp; HEX source</a><a href="native-top.png">Top view</a></nav></section><img class="native" src="native-review.png" width="1680" height="1700" alt="Six actual R6 review solids in an oblique view"><section class="notes"><details><summary>Fit, printing and revision history</summary><p>The existing mechanical blank is unchanged: a 13.90 × 30.50 mm opening, 0.10 mm nominal glass clearance and a frame face at Z13.59 mm. Every screen bezel is an exact 2.40 mm outward offset.</p><p>The preview cards show the modeled LCD footprint with illustrative content. The solid render shows the opaque glass model. Neither paints over missing frame material.</p><p>Target: 0.4 mm nozzle and 0.2 mm layers. These are review files, not a print release. Thin tips, color bonding and physical fit still require a sliced sample.</p><p>R5 was rejected. Its <a href="https://github.com/eduarbo/flan36/tree/main/design/proposals/frame-redesign-r5">frozen files</a> remain available as history. R6 requires approval before integration.</p></details><p class="hash">Master SHA256: '''+digest+'''</p></section></main></body></html>'''
    (OUT/'index.html').write_text(page)
    print('Built R6 mobile gallery with six distinct exact previews and direct image links')
if __name__=='__main__':run()
