#!/usr/bin/env python3
"""Mobile R7 approval gallery: selected Hanafuda and six new alternatives.
SPDX-License-Identifier: GPL-3.0-or-later
"""
import hashlib,html,json,os,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'design/proposals/frame-redesign-r7';OUT=ROOT/'docs/frame-proposals'
def run():
    master=json.loads((SOURCE/'master.json').read_text());check=json.loads((SOURCE/'geometry-check.json').read_text())
    digest=hashlib.sha256((SOURCE/'master.json').read_bytes()).hexdigest();assert check['master_sha256']==digest
    dest=OUT/'r7';dest.mkdir(parents=True,exist_ok=True)
    assets=['collection.png','mecha.png','kumiko.png','native-review.png','native-top.png']+[k+ext for k in master['styles'] for ext in ['-preview.svg','-card.png','-dimensioned.png','.svg']]
    for name in assets:shutil.copy2(SOURCE/name,dest/name)
    base='https://github.com/eduarbo/flan36/blob/main/design/proposals/frame-redesign-r7/'
    def card(key):
        s=master['styles'][key];name=html.escape(s['label']);code=s['code']
        palette=''.join(f'<span><i style="background:{c}"></i><code>{c}</code></span>' for c in s['palette'].values())
        return f'<article id="{key}"><a class="preview" href="r7/{key}-card.png" aria-label="Enlarge {code}: {name}"><img src="r7/{key}-preview.svg" width="240" height="560" alt="{code}: {name}, exact frame artwork" loading="lazy"></a><div class="replaces">{html.escape(s["tagline"])}</div><h2>{code} / {name}</h2><p>{html.escape(s["note"])}</p><div class="palette">{palette}</div><nav aria-label="{name} files"><a href="r7/{key}-dimensioned.png">Dimensions</a><a href="r7/{key}.svg" download>1:1 SVG ↓</a></nav></article>'
    groups=''
    for group in master['presentation']['collections']:
        family=group['name'].title();groups+=f'<section aria-labelledby="{group["name"]}"><h2 class="family" id="{group["name"]}">{family} <small>Choose one direction</small></h2><div class="grid">'+''.join(card(k) for k in group['keys'])+'</div></section>'
    css=CSS
    page=f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mecha &amp; Kumiko proposals · Flan36</title><style>{css}</style></head><body><main><a class="back" href="../">← 3D explorer</a><header><div class="status">R7 · Hanafuda selected · Mecha &amp; Kumiko awaiting choice</div><h1>Mecha &amp; Kumiko.</h1><p>Three alternatives for each family. Exact dimensions, solid colors and flat inlays on the current 24 × 56 mm frame. Tap any design to enlarge it.</p></header><section class="kept"><a href="r7/hanafuda-card.png"><img src="r7/hanafuda-preview.svg" width="96" height="224" alt="Selected Hanafuda, retained unchanged"></a><div><div class="status">Selected</div><h2>Hanafuda stays.</h2><p>Its shapes and palette are retained exactly from R6. The six options below are new proposals; artwork integration follows your selection.</p><nav><a href="r7/hanafuda-dimensioned.png">Hanafuda dimensions</a><a href="r7/hanafuda.svg" download>1:1 SVG ↓</a></nav></div></section>{groups}<section class="notes"><h2>The drawings are the geometry.</h2><p>The six alternatives below are rendered from actual review solids. Their color volumes are checked against the same millimetre paths used in the previews.</p><nav><a href="{base}Artwork-R7.FCStd">FreeCAD review</a><a href="{base}master.json">Dimensions &amp; HEX source</a><a href="r7/native-top.png">Top view</a></nav></section><img class="native" src="r7/native-review.png" width="1680" height="1700" alt="Six Mecha and Kumiko review solids"><section class="notes"><details><summary>Fit, printing and references</summary><p>The mechanical blank remains unchanged: a 13.90 × 30.50 mm opening, 0.10 mm nominal glass clearance, a Z13.59 mm frame face and a uniform 2.40 mm screen bezel.</p><p>Kumiko uses printed color inlays, not open wooden joinery. Its nominal lattice strips are 0.80–0.85 mm wide. The 0.4 mm nozzle / 0.2 mm layer target, fine intersections and physical fit still need a sliced sample.</p><p>The preview LCD is illustrative. The native views show the opaque glass model. No motif enters the display opening.</p><p>Pattern references: <a href="https://kumikowoodworking.com/products/category/auspicious-omens-motifs/">Tanihata</a> and <a href="https://www.shion-kumiko.com/order-guide/kumiko-patterns/">Shion Kumiko</a>. Kasane is an original diagonal composition. The designs use original paths, not traced commercial artwork.</p><p>The other R6 alternatives were rejected and are excluded from this selection. Their <a href="https://github.com/eduarbo/flan36/tree/main/design/proposals/frame-redesign-r6">historical files</a> remain available.</p></details><p class="hash">Master SHA256: {digest}</p></section></main></body></html>"""
    (OUT/'index.html').write_text(page)
    print('Built R7 gallery: selected Hanafuda, three Mecha and three Kumiko proposals')
CSS=':root{color-scheme:light;font:16px/1.5 system-ui,sans-serif;color:#253c37;background:#f6f5f0}*{box-sizing:border-box}body{margin:0}main{max-width:1180px;margin:auto;padding:28px 20px 60px}a{color:inherit;text-underline-offset:4px}a:focus-visible{outline:3px solid #527d63;outline-offset:4px;border-radius:4px}header{max-width:820px;margin:24px 0 32px}h1{font-size:clamp(32px,5vw,54px);line-height:1.1;margin:16px 0}h2{margin:0 0 10px;font-size:25px}p{margin:8px 0 16px}.status,.replaces{font-size:12px;letter-spacing:.065em;text-transform:uppercase;color:#576e60}.replaces{margin-bottom:6px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}article{background:#fffefa;border:1px solid #dce1d7;border-radius:16px;padding:22px;scroll-margin:20px}.preview{display:flex;height:340px;align-items:center;justify-content:center;margin-bottom:24px;border-radius:10px;transition:background .12s}.preview:hover{background:#f2f1e9}.preview img{height:100%;width:auto;max-width:100%}article p{font-size:14px;min-height:104px;color:#4c6058}.palette{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;font-size:12px}.palette span{display:flex;gap:6px;align-items:center}.palette code{user-select:all}.palette i{width:14px;height:14px;border:1px solid #0002;border-radius:3px;flex-shrink:0}nav{display:flex;flex-wrap:wrap;gap:10px;margin:20px 0 0}nav a{padding:10px 12px;min-height:44px;border:1px solid #dce1d7;border-radius:8px;font-size:14px;text-decoration:none}nav a:hover{background:#edf1e8}.native{width:100%;height:auto;border-radius:16px;margin:18px 0}.notes{max-width:880px;margin:40px 0}.hash{overflow-wrap:anywhere;font-size:11px;color:#5d6d64}details{margin:25px 0}summary{cursor:pointer;padding:12px 0;min-height:44px}.back{display:inline-block;padding:8px 0;min-height:44px}@media(max-width:800px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.grid{grid-template-columns:1fr}article p{min-height:0}.preview{height:380px}main{padding:20px 16px}}\n\n.family{font-size:29px;margin:44px 0 20px}.family small{display:block;font-size:14px;font-weight:400;color:#617064;margin-top:4px}.kept{display:flex;align-items:center;gap:32px;padding:26px;background:#e9eddf;border-radius:16px;max-width:860px}.kept img{display:block}.kept p{max-width:570px}.kept a{flex-shrink:0}@media(max-width:520px){.kept{gap:20px;padding:20px}.kept img{width:65px;height:auto}.kept p{font-size:14px}.kept nav{gap:6px}.kept nav a{padding:8px;font-size:12px}}\n'
if __name__=='__main__':
    if os.environ.get('FLAN36_ARTWORK_REVIEW')=='frame-redesign-r7':run()
    else:
        from build_frame_review_r8 import run as current
        current(CSS)
