#!/usr/bin/env python3
"""Public, mobile-friendly approval page from frozen frame review artifacts.
SPDX-License-Identifier: GPL-3.0-or-later
"""
import hashlib,html,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'design/proposals/frame-redesign-r5';OUT=ROOT/'docs/frame-proposals'
def run():
    master=json.loads((SOURCE/'master.json').read_text());check=json.loads((SOURCE/'geometry-check.json').read_text())
    digest=hashlib.sha256((SOURCE/'master.json').read_bytes()).hexdigest();assert check['master_sha256']==digest
    OUT.mkdir(parents=True,exist_ok=True)
    for name in ['collection.png','collection-a.png','collection-b.png','native-review.png',*[k+'-preview.svg' for k in master['styles']]]:shutil.copy2(SOURCE/name,OUT/name)
    shutil.copy2(ROOT/'design/proposals/display-seam-r1/comparison.png',OUT/'seam-comparison.png')
    base='https://github.com/eduarbo/flan36/blob/main/design/proposals/frame-redesign-r5/'
    cards=''
    for key,s in master['styles'].items():
        palette=''.join(f'<span><i style="background:{c}"></i><code>{c}</code></span>' for c in dict.fromkeys(s['palette'].values()))
        cards+=f'<article id="{key}"><a class="preview" href="{base}{key}-dimensioned.png" aria-label="{s["label"]}: dimensions"><img src="{key}-preview.svg" width="240" height="560" alt="{s["label"]} exact frame proposal" loading="lazy"></a><h2>{s["label"]}</h2><p>{html.escape(s["note"])}</p><div class="palette">{palette}</div><nav><a href="{base}{key}-dimensioned.png">Dimensions</a><a href="{base}{key}.svg">1:1 SVG</a></nav></article>'
    page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Frame proposals · Flan36</title><style>
    :root{color-scheme:light;font:16px/1.5 system-ui,sans-serif;color:#253c37;background:#f6f5f0}*{box-sizing:border-box}body{margin:0}main{max-width:1180px;margin:auto;padding:28px 20px 60px}a{color:inherit;text-underline-offset:4px}header{max-width:820px;margin:24px 0 32px}h1{font-size:clamp(32px,5vw,54px);line-height:1.1;margin:16px 0}h2{margin:0 0 10px;font-size:23px}p{margin:8px 0 16px}.status{font-size:13px;letter-spacing:.08em;text-transform:uppercase;color:#576e60}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}article{background:#fffefa;border:1px solid #dce1d7;border-radius:16px;padding:22px;scroll-margin:20px}.preview{display:flex;height:290px;align-items:center;justify-content:center;margin-bottom:24px}.preview img{height:100%;width:auto;max-width:100%;filter:drop-shadow(0 2px 1px #00000010)}article p{font-size:14px;min-height:85px;color:#4c6058}.palette{display:flex;flex-wrap:wrap;gap:7px 16px;font-size:12px}.palette span{display:flex;gap:6px;align-items:center}.palette i{width:13px;height:13px;border:1px solid #0002;border-radius:3px}nav{display:flex;gap:18px;margin:20px 0 0}nav a{padding:8px 0;font-size:14px}.native{width:100%;height:auto;border-radius:16px;margin:18px 0}.notes{max-width:850px;margin:40px 0}.notes code{overflow-wrap:anywhere;font-size:12px}details{margin:25px 0}summary{cursor:pointer;padding:12px 0}@media(max-width:800px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.grid{grid-template-columns:1fr}article p{min-height:0}.preview{height:330px}main{padding:20px 16px}}
    </style></head><body><main><a href="../">← 3D explorer</a><header><div class="status">R5 · awaiting design approval</div><h1>Six frames, drawn to fit.</h1><p>Exact curves, solid colors and flush details. These proposals share the 24 × 56 mm envelope and the corrected, glass-centered opening. They are separate from the six existing designs in the explorer.</p><p>Choose a design to inspect its dimensions. The SVG, editable FreeCAD review and render use the same millimetre paths.</p></header><div class="grid">'''+cards+'''</div><section class="notes"><h2>Actual 3D review geometry</h2><p>The render below uses the review solids. The dark rectangle is the modeled glass. The green LCD preview in the cards is contextual and does not fill missing material around the glass.</p></section><img class="native" src="native-review.png" width="1680" height="990" alt="Six exact frame review solids"><section class="notes"><nav><a href="'''+base+'''Artwork-R5.FCStd">FreeCAD review</a><a href="'''+base+'''master.json">Dimensions &amp; HEX source</a></nav><details><summary>Display seam and print targets</summary><p>The 13.90 × 30.50 mm opening leaves 0.10 mm nominal glass clearance. The frame face remains at Z13.59 mm. No display translation or added stack height. The five approved bezels retain an exact 2.40 mm offset.</p><p>The comparison uses actual PCB, glass, frame and supports. It removes the broad pale side strips in the sampled views. This does not guarantee an invisible joint from every angle or a measured printed fit.</p><p>0.4 mm nozzle / 0.2 mm layer target; physical fit, thin motif tips and toolpath retention still need qualification.</p></details><code>Master SHA256: '''+digest+'''</code></section><img class="native" src="seam-comparison.png" width="1600" height="1040" alt="Current and corrected display seam at four viewing angles"></main></body></html>'''
    (OUT/'index.html').write_text(page)
    print('Built mobile approval page with six distinct exact previews')
if __name__=='__main__':run()
